-- 海运运价记录表
CREATE TABLE IF NOT EXISTS freight_rates (
    id                  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    carrier             VARCHAR(64)  DEFAULT '' COMMENT '承运人',
    pol                 VARCHAR(128) NOT NULL   COMMENT '起运港',
    pol_code            VARCHAR(10)  DEFAULT '' COMMENT '起运港五字码',
    pod                 VARCHAR(128) NOT NULL   COMMENT '目的港',
    pod_code            VARCHAR(10)  DEFAULT '' COMMENT '目的港五字码',
    f20gp               VARCHAR(32)  DEFAULT '' COMMENT '20GP 价格',
    f40gp               VARCHAR(32)  DEFAULT '' COMMENT '40GP 价格',
    f40hc               VARCHAR(32)  DEFAULT '' COMMENT '40HC 价格',
    validity_start_time VARCHAR(16)  DEFAULT '' COMMENT '有效期开始日期',
    validity_end_time   VARCHAR(16)  DEFAULT '' COMMENT '有效期结束日期',
    etd                 VARCHAR(16)  DEFAULT '' COMMENT '预计开航日期',
    eta                 VARCHAR(16)  DEFAULT '' COMMENT '预计到港日期',
    pol_pod_tt          VARCHAR(16)  DEFAULT '' COMMENT '航程（天）',
    vessel              VARCHAR(128) DEFAULT '' COMMENT '船名',
    voyage              VARCHAR(64)  DEFAULT '' COMMENT '航次',
    cut_off_time        VARCHAR(16)  DEFAULT '' COMMENT '截关日期',
    port_closing_time   VARCHAR(16)  DEFAULT '' COMMENT '集港日期',
    commodity           VARCHAR(255) DEFAULT '' COMMENT '品名',
    dnd                 VARCHAR(255) DEFAULT '' COMMENT '免箱免堆',
    weight_limit        VARCHAR(64)  DEFAULT '' COMMENT '限重',
    remark              TEXT                    COMMENT '备注',
    source_user_id      VARCHAR(64)  DEFAULT '' COMMENT '来源用户 ID',
    source_chat_id      VARCHAR(64)  DEFAULT '' COMMENT '来源会话 ID',
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_pol_pod    (pol, pod),
    INDEX idx_carrier    (carrier),
    INDEX idx_validity   (validity_start_time, validity_end_time),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='海运运价记录表';
